name: Build MolyuuOS Repository

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container: 
      image: archlinux:base-devel
      options: --privileged

    steps:
    - name: Prepare environment
      shell: 'script -q -e -c "bash {0}"'
      env: 
        GPG_SIGNING_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.PASSPHRASE }}
      run: |
        pacman-key --init
        pacman-key --populate archlinux
        mkdir -p /etc/gnupg && echo "auto-key-retrieve" >> /etc/gnupg/gpg.conf
        echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist\n" >> /etc/pacman.conf
        pacman -Syu --noconfirm
        pacman -S --noconfirm python python-mako python-requests python-distutils-extra base-devel libarchive git curl wget sudo bash arch-install-scripts
        useradd -m -G wheel -s /bin/bash builder
        echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        echo $GPG_SIGNING_KEY | base64 --decode > gpg.key || true
        su builder -c "gpg --batch --passphrase $GPG_PASSPHRASE --import gpg.key"
        rm gpg.key

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build repository and build rootfs
      env: 
        GPG_PASSPHRASE: ${{ secrets.PASSPHRASE }}
      run: |
        chown -R builder:builder .
        su builder -c "cd $PWD && python -u build.py --sign $GPG_PASSPHRASE"
        su builder -c "cd $PWD/workspace/output && rm molyuu.db molyuu.db.sig && rm molyuu.files molyuu.files.sig && mv molyuu.db.tar.xz molyuu.db && mv molyuu.db.tar.xz.sig molyuu.db.sig && mv molyuu.files.tar.xz molyuu.files && mv molyuu.files.tar.xz.sig molyuu.files.sig || true"

    - name: "Get current date"
      run: |
        echo "builddate=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
      id: date

    - name: Create release and upload artifacts
      id: upload-artifacts
      continue-on-error: true
      uses: ncipollo/release-action@v1
      with:
        artifactErrorsFailBuild: true
        removeArtifacts: true
        allowUpdates: true
        generateReleaseNotes: true
        tag: latest
        name: ${{ steps.date.outputs.builddate }}
        artifacts: "workspace/output/*"
        body: |
          MolyuuOS x86_64 repo packages
